apiVersion: v1
kind: Namespace
metadata:
  name: renovai-api

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-config
  namespace: renovai-api
data:
  SPRING_PROFILES_ACTIVE: "prod"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-api
  namespace: renovai-api
  labels:
    app: springboot-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: springboot-api

  template:
    metadata:
      labels:
        app: springboot-api

    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: springboot-app

          image: "kauaribeiro/renovai-api:latest"

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: springboot-config

            - secretRef:
                name: springboot-secrets

          resources:
            requests:
              cpu: "200m"
              memory: "768Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: renovai-api

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer

  selector:
    app: springboot-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
