apiVersion: v1
kind: Secret
metadata:
  name: springboot-secrets
  namespace: renovai-api
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "url do banco"
  SPRING_DATASOURCE_USERNAME: "usuario do banco"
  SPRING_DATASOURCE_PASSWORD: "senha do banco"
  JWT_SECRET: "32-chars"
  JWT_EXPIRATION: "86400000"
  SERVER_SERVLET_CONTEXT_PATH: "/api"